// <auto-generated />
namespace SimpleJob.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dosyatablE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dosyatablE));
        
        string IMigrationMetadata.Id
        {
            get { return "202205120533166_dosyatablE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
